---
#
# Filename:     master.yml
# Description:  Master Playbook
# Author:       Steve Pedersen
# Company:      Academic Technology
#


#
# Play for common tasks that apply to all nodes 
#
# - name: apply configuration to all nodes
#   hosts:  all
#   remote_user:  root
#   roles:
#     - common



#
# Play for deployment of AT PHP Framework based applications
#
- name: Configure and deploy content for PHP applications
  hosts:  webservers
  gather_facts: no
  become: yes
  become_user:  root
  roles:    
    - {role: php_app, tags: php_app }



#
# Plays for deployment of Fresca application
# Deploy can be for test and/or production
#
- name: Configure and deploy Fresca application on Test
  hosts:  fresca-test
  gather_facts: no
  become: yes
  become_user:  root
  roles:
    - role: shibboleth
      when: test
      tags: ['shibboleth', 'shibboleth-fresca']
    - role: fresca
      when: test
      tags: ['fresca', 'fresca-test']


- name: Configure and deploy Fresca application on Production
  hosts:  fresca-production
  gather_facts: no
  become: yes
  become_user:  root
  roles:      
    - role: shibboleth
      when: production
      tags: ['shibboleth', 'shibboleth-fresca']
    - role: fresca
      when: production
      tags: ['fresca', 'fresca-production']

# - name: Configure and deploy Fresca application on Test
#   hosts:  fresca-test
#   gather_facts: no
#   become: yes
#   become_user:  root
#   roles:      
#     - { role: shibboleth,
#         when: "(({{ app_name }} == fresca) and (test))",
#         tags: ['shibboleth', 'shibboleth-fresca'] }
#     - { role: fresca,
#         when: "(({{ app_name }} == fresca) and (test))",
#         tags: ['fresca', 'fresca-test'] }