---
#
# Filename:     master.yml
# Description:  Master Playbook
# Author:       Steve Pedersen
# Company:      Academic Technology
#


#
# Play for deployment of AT PHP Framework based applications
#
- name: Configure and deploy content for PHP applications
  hosts:  webservers
  gather_facts: no
  become: yes
  become_user:  root
  roles:    
    - role: php_app 
      tags: php_app



#
# Plays for deployment of Fresca application
# Deploy can be for test and/or production
#
- name: Configure and deploy Fresca application on Test
  hosts:  fresca-test
  gather_facts: no
  become: yes
  become_user:  root
  roles:
    - role: shibboleth
      when: shib_required
      tags: ['shibboleth', 'shibboleth-fresca']
    - role: fresca
      tags: ['fresca', 'fresca-test']
    - role: xapian
      tags: xapian


- name: Configure and deploy Fresca application on Production
  hosts:  fresca-production
  gather_facts: no
  become: yes
  become_user:  root
  roles:      
    - role: shibboleth
      when: shib_required
      tags: ['shibboleth', 'shibboleth-fresca']
    - role: fresca
      tags: ['fresca', 'fresca-production']
    - role: xapian
      tags: xapian
