---
# Fresca specific packages


#
# Package manager installations
# 
- name: apt-get update and upgrade
  apt:  upgrade=yes update_cache=yes state=latest cache_valid_time=3600
  notify: restart apache2
  tags: apt

- name: install fresca packages
  apt:  name={{ item }} update_cache=yes state=latest cache_valid_time=3600
  with_items: "{{ fresca_packages }}"
  notify: restart apache2
  tags: apt


#
# Xapian - build binary packages from source in order to install php5-xapian
#
- name: build xapian-bindings dependencies
  shell: apt-get build-dep -y xapian-bindings warn=no
  tags: xapian

- name: install xapian dependencies
  apt:  name={{ item }} update_cache=yes state=latest
  with_items: "{{ xapian_dependencies }}"
  notify: restart apache2
  tags: xapian

- name: clear any pre-existing xapian dir in root folder
  file: path=~/xapian state=absent
  tags: xapian

- name: create xapian dir to work in
  file: path=~/xapian state=directory mode=0755
  tags: xapian

- name: get xapian-bindings from source
  shell:  cd ~/xapian && apt-get source xapian-bindings warn=no
  tags: xapian

- name: remove debian control and stamp files
  shell:  cd ~/xapian/xapian-bindings-1.2.* && rm -f debian/control debian/*-stamp
  tags: xapian

- name: alter files in debian folder to permit php bindings
  shell:  "cd ~/xapian/xapian-bindings-1.2.* && echo php > debian/bindings-to-package"
  tags: xapian

- name: alter env values then pipe php values into package
  shell:  "cd ~/xapian/xapian-bindings-1.2.* && env PHP_VERSIONS=5 debian/rules maint && sed -i '/^X-Dummy:/d' debian/control"
  tags: xapian

- name: build the php5-xapian debian package (this may take a couple minutes)
  shell:  "cd ~/xapian/xapian-bindings-1.2.* && env DEB_BUILD_OPTIONS=nocheck debuild -e PHP_VERSIONS=5 -us -uc"
  tags: xapian

- name: install the php5-xapian package we just built!
  shell:  "cd ~/xapian && dpkg -i php5-xapian_*.deb"
  notify: restart apache2
  register: php_xapian
  tags: xapian

- name: enable xapian extension
  copy: 
    content: "extension=xapian.so"
    dest: /etc/php5/mods-available/xapian.ini
  tags: xapian

- name: create symlink for xapian extension
  file:
    src: /etc/php5/mods-available/xapian.ini      #file to link to
    path: /etc/php5/apache2/conf.d/20-xapian.ini  #the symlink
    state: link
    mode: 0777
  notify: restart apache2
  tags: xapian
#
# End of Xapian install
#


- name: apt-get update and upgrade
  apt:  upgrade=yes update_cache=yes state=latest cache_valid_time=3600
  register: result
  until: result.stderr == ""
  retries: 3
  tags: loopy
