---
# Playbook for Fresca



- include: install-packages.yml   # fresca specific packages
  tags: packages
- include: git.yml                # clone fresca repo
  tags: git
- include: virtualhosts.yml       # transfer ssl certs, enable virtual host
  tags: vhost
- include: postgres.yml           # createdb
  tags: postgres
- include: config.yml             # remaining tasks
  tags: config


#
# Finish remaining tasks
#

- name: Copy fresca.conf virtualhost file production
  template: src=fresca.vhost.conf.j2 dest=/root/cheese/fresca.conf mode=0644
  tags: confy

