---
# Tasks for Fresca database


# Ansible requires these modules on remote node in order to user postgres
- name: Install prerequisites for postgres to be setup by ansible
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - libpq-dev
    - python-psycopg2
  register: python_prereqs
  tags: pg-packages


# CreateDB fresca, createUser fresca
- name: DropDB first
  postgresql_db: name=fresca login_user=apps state=absent

- name: Add postgreSQL fresca role
  postgresql_user: name=fresca role_attr_flags=SUPERUSER
  become: true
  become_user: postgres
  notify: restart postgres

- name: Create fresca database
  postgresql_db:
    name: fresca
    login_user: apps
    template: 'template0'
    encoding: 'UNICODE'
  notify: restart postgres



# Manual removal of these packages. they are not needed
- name: Uninstall python modules used by ansible for postgres plays
  apt: name={{ item }} update_cache=yes state=absent
  with_items:
    - libpq-dev
    - python-psycopg2
  when: python_prereqs|changed or fresca
  tags: pg-packages