---
# Playbook for Apache-Fresca virtual host configuration
- include_vars: secrets.yml


# Copy SSL certs
- name: create certs folder test
  file: path=/etc/apache2/certs state=directory mode=0755
  when: test

- name: copy SSLCertificateFile test
  copy: 
    content: "{{ cert_file_test }}"
    dest: /etc/apache2/certs/fresca.test.at.sfsu.edu.2016.cer
    mode: 0644
  when: test

- name: copy SSLCertificateKeyFile test
  copy: 
    content: "{{ cert_key_test }}"
    dest: /etc/apache2/certs/fresca.test.at.sfsu.edu.2016.key
    mode: 0600
  when: test

- name: copy SSLCertificateFile production
  copy: 
    content: "{{ cert_file_prod }}"
    dest: /etc/apache2/fresca.calstate.edu.2015.cer
    mode: 0644
  when: production

- name: copy SSLCertificateKeyFile production
  copy: 
    content: "{{ cert_key_prod }}"
    dest: /etc/apache2/fresca.calstate.edu.2015.key
    mode: 0600
  when: production


# Copy virtual host file and enable site
- name: copy fresca.conf virtualhost file test
  template: src=fresca.vhost.conf.j2 dest=/etc/apache2/sites-available/fresca.conf mode=0644
  when: test

- name: copy fresca.conf virtualhost file production
  template: src=fresca-vhost.prod.conf.j2 dest=/etc/apache2/sites-available/fresca.conf mode=0644
  when: production

- name: enable fresca virtualhost file
  command: a2ensite fresca

- name: Check that our config is valid
  command: apache2ctl configtest
  register: result
  ignore_errors: True

- name: Rolling back - Restoring old default virtualhost
  command: a2ensite 000-default
  when: result|failed

- name: Rolling back - Removing our virtualhost
  command: a2dissite fresca
  when: result|failed

- name: Rolling back - Ending playbook
  fail: msg="Configuration file is not valid. Please check that before re-running the playbook."
  when: result|failed

- name: Deactivates the default virtualhost
  command: a2dissite 000-default

- name: Deactivates the default ssl virtualhost
  command: a2dissite default-ssl
  notify: restart apache2