---
# Playbook for Apache-Fresca virtual host configuration
- include_vars: secrets.yml


# Copy SSL certs
- name: copy SSLCertificateFile
  copy: 
    content: "{{ cert_file }}"
    dest: /etc/apache2/certs/fresca.test.at.sfsu.edu.2016.cer
    mode: 0644

- name: copy SSLCertificateKeyFile
  copy: 
    content: "{{ cert_key }}"
    dest: /etc/apache2/certs/fresca.test.at.sfsu.edu.2016.key
    mode: 0600


# Copy virtual host file and enable site
- name: copy fresca.conf virtualhost file
  template: src=fresca.vhost.conf.j2 dest=/etc/apache2/sites-available/fresca.conf mode=0644

- name: enable fresca virtualhost file
  command: a2ensite fresca

- name: Check that our config is valid
  command: apache2ctl configtest
  register: result
  ignore_errors: True

- name: Rolling back - Restoring old default virtualhost
  command: a2ensite 000-default
  when: result|failed

- name: Rolling back - Removing our virtualhost
  command: a2dissite fresca
  when: result|failed

- name: Rolling back - Ending playbook
  fail: msg="Configuration file is not valid. Please check that before re-running the playbook."
  when: result|failed

- name: Deactivates the default virtualhost
  command: a2dissite 000-default

- name: Deactivates the default ssl virtualhost
  command: a2dissite default-ssl
  notify: restart apache2