---
# Playbook for Apache-Fresca virtual host configuration



- name: copy fresca.conf virtualhost file
  template: src=fresca.conf.j2 dest=/etc/apache2/sites-available/fresca.conf mode=0644
  tags: [fresca, vhost]

- name: disable 000-default
  shell: a2dissite 000-default.conf
  tags: [fresca, vhost]

- name: enable fresca virtualhost file
  shell: a2ensite fresca.conf
  tags: [fresca, vhost]
