---
# Copy shibboleth files & pems for test/production


#
# Test
#
- name: Copy all test shibboleth files
  copy: src=test/ dest=/etc/shibboleth
  when: test

#
# Production
#
- name: Copy all production shibboleth files
  copy: src=prod/ dest=/etc/shibboleth
  when: production

- name: Copy production inc-md-cert pem
  copy: 
    content: "{{ inc_md_cert_pem }}"
    dest: /etc/shibboleth/inc-md-cert.pem
    mode: 0644
  when: production

#
# All
#
- name: Copy incommon pem
  copy: 
    content: "{{ incommon_pem }}"
    dest: /etc/shibboleth/incommon.pem
    mode: 0644

- name: Copy sp-cert pem
  copy: 
    content: "{{ sp_cert_pem }}"
    dest: /etc/shibboleth/sp-cert.pem
    mode: 0644

- name: Copy sp-key pem
  copy: 
    content: "{{ sp_key_pem }}"
    dest: /etc/shibboleth/sp-key.pem
    mode: 0644
  notify: restart shibd
