---
# Copy shibboleth files & pems for test/production
- include_vars: test-secrets.yml
- include_vars: prod-secrets.yml


#
# Test
#
# file copy recursive due to trailing '/' on src
- name: Copy all test shibboleth files
  copy: src=test/ dest=/etc/shibboleth
  when: test

- name: Copy test incommon pem
  copy: 
    content: "{{ test_incommon_pem }}"
    dest: /etc/shibboleth/incommon.pem
    mode: 0644
  when: test
  tags: pems

- name: Copy test sp-cert pem
  copy: 
    content: "{{ test_sp_cert_pem }}"
    dest: /etc/shibboleth/sp-cert.pem
    mode: 0644
  when: test
  tags: pems

- name: Copy test sp-key pem
  copy: 
    content: "{{ test_sp_key_pem }}"
    dest: /etc/shibboleth/sp-key.pem
    mode: 0644
  when: test
  notify: restart shibd
  tags: pems


#
# Production
#
- name: Copy all production shibboleth files
  copy: src=prod/ dest=/etc/shibboleth
  when: production

- name: Copy production inc-md-cert pem
  copy: 
    content: "{{ prod_inc_md_cert_pem }}"
    dest: /etc/shibboleth/inc-md-cert.pem
    mode: 0644
  when: production
  tags: pems

- name: Copy production incommon pem
  copy: 
    content: "{{ prod_incommon_pem }}"
    dest: /etc/shibboleth/incommon.pem
    mode: 0644
  when: production
  tags: pems

- name: Copy production sp-cert pem
  copy: 
    content: "{{ prod_sp_cert_pem }}"
    dest: /etc/shibboleth/sp-cert.pem
    mode: 0644
  when: production
  tags: pems

- name: Copy production sp-key pem
  copy: 
    content: "{{ prod_sp_key_pem }}"
    dest: /etc/shibboleth/sp-key.pem
    mode: 0644
  when: production
  notify: restart shibd
  tags: pems