---
# Copy shibboleth files & generate pems for test/production


#
# Test
#
- name: Copy all test shibboleth files
  copy: src=test/ dest=/etc/shibboleth
  when: test



#
# Production
#

- name: Copy all production shibboleth files
  copy: src=prod/ dest=/etc/shibboleth
  when: production




