---
# Main playbook for Shibboleth-role tasks


- include: install-packages.yml     # shibboleth specific packages
  tags: packages
- include: copy-files.yml           # shib files and pems
  tags: pems