---
# Handler for fresca role



- name: restart postgres
  service: name=postgresql state=restarted

- name: restart shibd
  service: name=shibd state=restarted

- name: restart apache2
  service: name=apache2 state=restarted