---
# fresca-production specific variables

# uses the string of hostname up until the first "."
app_name: "{{ inventory_hostname_short }}"

shib_required: true
entity_id: https://idp.sfsu.edu/idp/shibboleth
metadata_provider_path: /etc/shibboleth/idp-minkar-metadata.xml

# used to trigger production specific tasks within roles shared with test
fresca: true
instance: production
production: true
test: false
