---
# Configuration of PHP mods-available


# Create mods-available configuration files
# TODO: look for a way to insert a template at EOF, if file exists -- (lineinfile module)
- name: create opcache from template
  template: src=opcache.j2 dest=/etc/php5/mods-available/opcache.ini
  tags: mods-available

- name: config timezone
  template: src=timezone.j2 dest=/etc/php5/mods-available/timezone.ini
  tags: mods-available

- name: config pecl_http
  template: src=pecl_http.j2 dest=/etc/php5/mods-available/pecl_http.ini
  tags: mods-available

- name: config memory limit
  template: src=memory_limit.j2 dest=/etc/php5/mods-available/memory_limit.ini
  tags: mods-available

- name: config upload
  template: src=upload.j2 dest=/etc/php5/mods-available/upload.ini
  tags: mods-available


# Enable PHP5 modules
- name: enable php5 opcache module
  shell: php5enmod opcache

- name: enable php5 pecl_http module
  shell: php5enmod pecl_http

- name: enable php5 memory_limit module
  shell: php5enmod memory_limit

- name: enable php5 upload module
  shell: php5enmod upload

- name: enable php5 timezone module
  shell: php5enmod timezone
