---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp 
  apt: name=ntp state=present
  tags: ntp

# TODO: setup a ntp template
- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false