---
#   Uses core package modules install packages.

- name: apt-get update and upgrade
  apt:  upgrade=yes update_cache=yes state=latest
  notify: restart apache2
  tags:
    - packages 
    - apt

# apt_packages are defined in roles/web/vars/main.yml
- name: install packages apache and php etc
  apt:  name={{ item }} update_cache=yes state=latest
  with_items: "{{ apt_packages }}"
  notify: restart apache2
  tags:
    - packages 
    - apt

- name: get node from source
  get_url: url=https://deb.nodesource.com/setup dest=/usr/nodesource
  tags:
    - packages 
    - node

- name: install nodesource via bash
  shell: /usr/nodesource | /bin/bash - 
  tags:
    - packages 
    - node
  notify: remove nodesource file

- name: install less with npm
  npm:  name=less global=yes state=latest
  tags:
    - packages 
    - npm

- name: install pecl_http-1.7.6
  shell: "yes \"\" | pecl install pecl_http-1.7.6"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  tags: 
    - packages
    - pecl
    - pear

- name: create smarty directory
  file: path=/usr/share/php/smarty state=directory mode=0755

- name: install smarty
  unarchive: src=https://github.com/smarty-php/smarty/archive/v2.6.29.tar.gz dest=/usr/share/php/smarty copy=no
  tags:
    - packages 
    - smarty

- name: move smarty files
  command: cp -R /usr/share/php/smarty/smarty-2.6.29/libs/. /usr/share/php/smarty
  tags:
    - packages 
    - smarty

- name: remove smarty install directory
  file: path=/usr/share/php/smarty/smarty-2.6.29 state=absent
  tags:
    - packages 
    - smarty
