---
# Playbook for initial setup of postgres

# Ansible requires these modules on remote node in order to user postgres
- name: install prerequisites for postgres to be setup by ansible
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - libpq-dev
    - python-psycopg2
  register: python_prereqs
  tags:
    - packages

#- debug: var=python_prereqs.results[0].cache_updated

- name: add postgreSQL generic user with name apps
  postgresql_user: name=apps role_attr_flags=SUPERUSER
  become: true
  become_user: postgres

- name: establish trust relationship for generic user
  lineinfile: 
    dest: /etc/postgresql/9.3/main/pg_hba.conf
    line: "\nlocal\tall\t\tapps\t\t\t\t\ttrust\nhost\tall\t\tapps\t\t127.0.0.1/0\t\tmd5"
    state: present
    insertafter: EOF
    backup: yes

- name: revoke local access to database by removing local all all peer
  lineinfile: 
    dest: /etc/postgresql/9.3/main/pg_hba.conf
    regexp: (local   all             all                                     peer)
    state: absent
    backup: yes

# Manual removal of these packages. they are not needed
- name: uninstall python modules used by ansible for postgres plays
  apt: name={{ item }} update_cache=yes state=absent
  with_items:
    - libpq-dev
    - python-psycopg2
  when: python_prereqs|changed and not fresca
  tags:
    - packages  