---

fresca_packages:
  - php5-gd
  - imagemagick
  - php5-imagick
  - markdown
  - libmarkdown-php
  - gcc
  # - xapian-tools
  # - libxapian-dev

xapian_dependencies:
  - php5-dev
  - php5-cli
  - devscripts